// T-0203b AC11 (D-0053 §1): supabase/scripts/vendor.mjs.
import { test } from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import {
  cpSync,
  mkdtempSync,
  mkdirSync,
  readFileSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, "..", "..", "..");
const SCRIPT = path.join(REPO_ROOT, "supabase", "scripts", "vendor.mjs");
const VENDOR_DIR = path.join(REPO_ROOT, "supabase", "functions", "_shared", "vendor");

test("AC11: vendor.mjs --check exits 0 on the committed tree", () => {
  assert.doesNotThrow(() => execFileSync("node", [SCRIPT, "--check"], { cwd: REPO_ROOT }));
});

test("AC11: --check with one changed engine source line exits 1 and names the differing vendor file", () => {
  const root = mkdtempSync(path.join(tmpdir(), "vendor-root-"));
  try {
    mkdirSync(path.join(root, "packages", "engine"), { recursive: true });
    mkdirSync(path.join(root, "packages", "shared"), { recursive: true });
    cpSync(
      path.join(REPO_ROOT, "packages", "engine", "src"),
      path.join(root, "packages", "engine", "src"),
      { recursive: true },
    );
    cpSync(
      path.join(REPO_ROOT, "packages", "shared", "src"),
      path.join(root, "packages", "shared", "src"),
      { recursive: true },
    );
    // node_modules resolution (ajv, etc.) comes from the real workspace, via symlinks.
    symlinkSync(path.join(REPO_ROOT, "node_modules"), path.join(root, "node_modules"));
    symlinkSync(
      path.join(REPO_ROOT, "packages", "shared", "node_modules"),
      path.join(root, "packages", "shared", "node_modules"),
    );

    const timePath = path.join(root, "packages", "engine", "src", "time.ts");
    const original = readFileSync(timePath, "utf8");
    const changed = original.replace(
      "return Math.round((dateUtcMs(to) - dateUtcMs(from)) / DAY_MS);",
      "return Math.round((dateUtcMs(to) - dateUtcMs(from)) / DAY_MS) + 0;",
    );
    assert.notEqual(changed, original, "fixture edit did not match packages/engine/src/time.ts");
    writeFileSync(timePath, changed, "utf8");

    let stdout = "";
    let exitCode = 0;
    try {
      stdout = execFileSync("node", [SCRIPT, "--check", "--root", root], {
        cwd: REPO_ROOT,
        encoding: "utf8",
      });
    } catch (err) {
      stdout = err.stdout ?? "";
      exitCode = err.status;
    }
    assert.equal(exitCode, 1);
    assert.match(stdout.trim(), /^supabase\/functions\/_shared\/vendor\/engine\/time\.js$/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test("AC12: committed vendor files start with the GENERATED header", () => {
  const files = [
    path.join(VENDOR_DIR, "engine", "index.js"),
    path.join(VENDOR_DIR, "shared", "index.js"),
  ];
  for (const file of files) {
    const contents = readFileSync(file, "utf8");
    assert.match(contents, /^\/\/ GENERATED by supabase\/scripts\/vendor\.mjs/);
  }
});
