// Writes dist/tokens.css from src/tokens.json (D-0019, D-0208). Deterministic, no remote resources.
// Usage: node scripts/build-css.mjs [--out <file>]
//
// Emits, in one :root block:
//   --wl-color-<name>             flat Chalk & Iron colours (in use until the app screens migrate)
//   --wl-color-<state>-<name>     D-0208 state groups (plan, lift, rest, paper)
//   --wl-color-plan-coverage-0..N D-0208 coverage ramp, interpolated in OKLCH from coverage.from to .to
//   --wl-font-<role>              font stacks
//   --wl-radius-<name>, --wl-space-<name>  px values
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const pkgRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outFlag = process.argv.indexOf("--out");
const outFile =
  outFlag >= 0 && process.argv[outFlag + 1]
    ? resolve(process.argv[outFlag + 1])
    : resolve(pkgRoot, "dist/tokens.css");

const tokens = JSON.parse(readFileSync(resolve(pkgRoot, "src/tokens.json"), "utf8"));

const HEX = /^#[0-9A-F]{6}$/;
const STATES = ["plan", "lift", "rest", "paper"];

// --- OKLCH (Ottosson OKLab, sRGB D65). Hand-written so the build has no dependency; the tests
// check it against culori as the reference computation.
const toLinear = (c) => (c <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4);
const toGamma = (c) => (c <= 0.0031308 ? 12.92 * c : 1.055 * c ** (1 / 2.4) - 0.055);
const clamp01 = (c) => Math.min(1, Math.max(0, c));

function hexToOklch(hex) {
  const [r, g, b] = [1, 3, 5].map((i) => toLinear(parseInt(hex.slice(i, i + 2), 16) / 255));
  const l = Math.cbrt(0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b);
  const m = Math.cbrt(0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b);
  const s = Math.cbrt(0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b);
  const L = 0.2104542553 * l + 0.793617785 * m - 0.0040720468 * s;
  const A = 1.9779984951 * l - 2.428592205 * m + 0.4505937099 * s;
  const B = 0.0259040371 * l + 0.7827717662 * m - 0.808675766 * s;
  const C = Math.hypot(A, B);
  // Achromatic colours (white) have no hue; the ramp then keeps the other end's hue.
  const H = C < 1e-4 ? Number.NaN : (Math.atan2(B, A) * 180) / Math.PI;
  return { L, C, H };
}

function oklchToHex({ L, C, H }) {
  const h = Number.isNaN(H) ? 0 : (H * Math.PI) / 180;
  const A = C * Math.cos(h);
  const B = C * Math.sin(h);
  const l = (L + 0.3963377774 * A + 0.2158037573 * B) ** 3;
  const m = (L - 0.1055613458 * A - 0.0638541728 * B) ** 3;
  const s = (L - 0.0894841775 * A - 1.291485548 * B) ** 3;
  const rgb = [
    4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,
    -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,
    -0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s,
  ];
  return (
    "#" +
    rgb
      .map((c) => Math.round(clamp01(toGamma(clamp01(c))) * 255))
      .map((n) => n.toString(16).padStart(2, "0").toUpperCase())
      .join("")
  );
}

function oklchRamp(from, to, steps) {
  const a = hexToOklch(from);
  const b = hexToOklch(to);
  const ha = Number.isNaN(a.H) ? b.H : a.H;
  const hb = Number.isNaN(b.H) ? a.H : b.H;
  let dh = hb - ha;
  if (dh > 180) dh -= 360;
  if (dh < -180) dh += 360;
  const out = [];
  for (let i = 0; i < steps; i++) {
    if (i === 0) out.push(from);
    else if (i === steps - 1) out.push(to);
    else {
      const t = i / (steps - 1);
      out.push(oklchToHex({ L: a.L + (b.L - a.L) * t, C: a.C + (b.C - a.C) * t, H: ha + dh * t }));
    }
  }
  return out;
}

// --- Emit
const lines = [
  "/* Generated by @workoutlab/design-tokens from src/tokens.json. Do not edit. */",
  ":root {",
];
const emitted = new Set();
const push = (name, value) => {
  if (emitted.has(name)) throw new Error(`duplicate CSS variable ${name}`);
  emitted.add(name);
  lines.push(`  ${name}: ${value};`);
};

// Flat keys only: the nested state groups and the ramp spec are emitted below.
for (const [name, value] of Object.entries(tokens.color)) {
  if (typeof value === "string") push(`--wl-color-${name}`, value);
}
for (const state of STATES) {
  for (const [name, value] of Object.entries(tokens.color[state] ?? {})) {
    if (!HEX.test(value)) throw new Error(`color.${state}.${name} is not #RRGGBB: ${value}`);
    push(`--wl-color-${state}-${name}`, value);
  }
}
const cov = tokens.color.coverage;
if (cov) {
  if (cov.interpolation !== "oklch") throw new Error("color.coverage.interpolation must be oklch");
  if (!HEX.test(cov.from) || !HEX.test(cov.to)) throw new Error("color.coverage from/to not hex");
  if (!Number.isInteger(cov.steps) || cov.steps < 2) throw new Error("color.coverage.steps < 2");
  oklchRamp(cov.from, cov.to, cov.steps).forEach((hex, i) =>
    push(`--wl-color-plan-coverage-${i}`, hex),
  );
}
for (const [role, font] of Object.entries(tokens.font)) {
  push(`--wl-font-${role}`, font.family);
}
for (const group of ["radius", "space"]) {
  for (const [name, value] of Object.entries(tokens[group] ?? {})) {
    if (!Number.isFinite(value)) throw new Error(`${group}.${name} is not a number`);
    push(`--wl-${group}-${name}`, `${value}px`);
  }
}
lines.push("}", "");

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, lines.join("\n"), "utf8");
