// Writes dist/tokens.css from src/tokens.json (D-0019). Deterministic, no remote resources.
// Usage: node scripts/build-css.mjs [--out <file>]
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const pkgRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outFlag = process.argv.indexOf("--out");
const outFile =
  outFlag >= 0 && process.argv[outFlag + 1]
    ? resolve(process.argv[outFlag + 1])
    : resolve(pkgRoot, "dist/tokens.css");

const tokens = JSON.parse(readFileSync(resolve(pkgRoot, "src/tokens.json"), "utf8"));

const lines = [
  "/* Generated by @workoutlab/design-tokens from src/tokens.json. Do not edit. */",
  ":root {",
];
for (const [name, value] of Object.entries(tokens.color)) {
  lines.push(`  --wl-color-${name}: ${value};`);
}
for (const [role, font] of Object.entries(tokens.font)) {
  lines.push(`  --wl-font-${role}: ${font.family};`);
}
lines.push("}", "");

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, lines.join("\n"), "utf8");
