// T-0229 (D-0117, TR-0036): parseSessionPlan uses the Ajv standalone validator generated by
// gen:api, so it runs where code generation from strings is disabled (the PWA's CSP).
import { execFileSync } from "node:child_process";
import { readdirSync, readFileSync, statSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { Ajv2020 } from "ajv/dist/2020.js";
import { describe, expect, it } from "vitest";
import {
  VALIDATOR_PATH,
  generateSessionPlanValidator,
  standaloneValidatorSource,
} from "../scripts/gen-api.js";
import { parseSessionPlan } from "../src/index.js";
import { SESSION_PLAN_SCHEMA } from "../src/session-plan.schema.gen.js";
import { validateSessionPlan } from "../src/session-plan.validate.gen.js";
import { REPO_ROOT, clone, exampleOf } from "./support/spec.js";

type Obj = Record<string, unknown>;
const plan = exampleOf<{ plan: Obj }>("Workout").plan;
const noDeficits = (() => {
  const copy = clone(plan);
  delete copy.startDeficits;
  return copy;
})();
const generated: (value: unknown) => boolean = validateSessionPlan;
const PACKAGE_ROOT = fileURLToPath(new URL("..", import.meta.url));

describe("T-0229 AC1 behaviour unchanged", () => {
  it("T-0229 AC1 parseSessionPlan returns the input object itself", () => {
    const input = clone(plan);
    const result = parseSessionPlan(input);
    expect(result.ok).toBe(true);
    expect(result.ok && result.plan).toBe(input);
  });
});

describe("T-0229 AC2 session-plan.validate.gen.ts has no drift", () => {
  it("T-0229 AC2 is byte-identical to a fresh generation from api/openapi.yaml", async () => {
    expect(readFileSync(VALIDATOR_PATH, "utf8")).toBe(await generateSessionPlanValidator());
  });
});

describe("T-0229 AC3 the generated validator agrees with a runtime Ajv compile", () => {
  const runtime = new Ajv2020({ strict: true, allowUnionTypes: true }).compile(SESSION_PLAN_SCHEMA);

  function mutate(edit: (copy: Obj) => void): Obj {
    const copy = clone(plan);
    edit(copy);
    return copy;
  }
  const items = (copy: Obj) => copy.items as Obj[];

  // Every object row of the T-0102b AC17 table (test/session-plan.test.ts) except the throwing
  // getter, which never reaches the validator.
  const rows: Array<[string, unknown]> = [
    ["the AC7 (R7-E4) plan", plan],
    ["version 2 (newer app)", { ...clone(plan), version: 2 }],
    ["version 2 with other fields", { version: 2, steps: [] }],
    ["version 0", { ...clone(plan), version: 0 }],
    ["no startDeficits", noDeficits],
    ["no version", mutate((c) => delete c.version)],
    ['version "1"', { ...clone(plan), version: "1" }],
    ["{}", {}],
    ["[]", []],
    ["an extra key", { ...clone(plan), note: "x" }],
  ];
  const mutations: Array<[string, unknown]> = [
    ['an item with exerciseId ""', mutate((c) => (items(c)[0]!.exerciseId = ""))],
    [
      "an unknown SwapReason",
      mutate((c) => (items(c)[0]!.reasons as Obj[]).push({ code: "swap", reason: "bored" })),
    ],
    ["a missing warmup", mutate((c) => delete c.warmup)],
  ];

  it.each([...rows, ...mutations])("T-0229 AC3 %s", (_label, input) => {
    expect(generated(input)).toBe(runtime(input));
  });

  it("T-0229 AC3 the mutations are rejected and their valid neighbours accepted", () => {
    for (const [, input] of mutations) expect(generated(input)).toBe(false);
    // unicode: false keeps minLength: 1 meaning "non-empty" (D-0117 §1): a one-code-point astral
    // id (two UTF-16 units) is still accepted, as with the runtime compile.
    const astral = mutate((c) => (items(c)[0]!.exerciseId = "\u{1F3CB}"));
    expect(generated(astral)).toBe(true);
    expect(runtime(astral)).toBe(true);
    const swap = mutate((c) =>
      (items(c)[0]!.reasons as Obj[]).push({ code: "swap", reason: "variety" }),
    );
    expect(generated(swap)).toBe(true);
    expect(runtime(swap)).toBe(true);
  });
});

// The child runs with code generation from strings disabled: `eval` and `new Function` throw
// EvalError, as under the PWA's CSP `script-src 'self'` (D-0117 §4a).
const CHILD = `
const plans = JSON.parse(process.env.T0229_PLANS);
const out = {};
try { new Function("return 1"); out.newFunction = "no-throw"; }
catch (e) { out.newFunction = e?.constructor?.name ?? String(e); }
const { parseSessionPlan } = await import(${JSON.stringify(
  new URL("../src/index.ts", import.meta.url).href,
)});
out.plan = parseSessionPlan(plans.plan);
out.noDeficits = parseSessionPlan(plans.noDeficits);
const { Ajv2020 } = await import("ajv/dist/2020.js");
const { SESSION_PLAN_SCHEMA } = await import(${JSON.stringify(
  new URL("../src/session-plan.schema.gen.ts", import.meta.url).href,
)});
try { new Ajv2020({ strict: true, allowUnionTypes: true }).compile(SESSION_PLAN_SCHEMA); out.compile = "no-throw"; }
catch (e) { out.compile = e?.constructor?.name ?? String(e); }
process.stdout.write(JSON.stringify(out));
`;

describe("T-0229 AC4 parseSessionPlan works with code generation disabled", () => {
  it("T-0229 AC4 a --disallow-code-generation-from-strings child accepts the v1 plan and rejects noDeficits", () => {
    const stdout = execFileSync(
      process.execPath,
      [
        "--disallow-code-generation-from-strings",
        "--import",
        "tsx",
        "--input-type=module",
        "-e",
        CHILD,
      ],
      {
        cwd: PACKAGE_ROOT,
        encoding: "utf8",
        // The control compile logs Ajv's "Error compiling schema" dump on stderr; keep it quiet.
        stdio: ["ignore", "pipe", "pipe"],
        env: { ...process.env, T0229_PLANS: JSON.stringify({ plan, noDeficits }) },
      },
    );
    const out = JSON.parse(stdout) as Obj;
    // Controls: the flag is in force, and the old runtime-compile path fails under it (TR-0036).
    expect(out.newFunction).toBe("EvalError");
    expect(out.compile).not.toBe("no-throw");
    expect(out.compile).toBe("EvalError");
    expect(out.plan).toEqual({ ok: true, plan });
    expect(out.noDeficits).toEqual({ ok: false, error: "invalid" });
  });
});

function sourceFiles(dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = path.join(dir, entry);
    if (statSync(full).isDirectory()) {
      if (entry === "__tests__" || entry === "node_modules") continue;
      out.push(...sourceFiles(full));
    } else if (/\.(c|m)?[jt]sx?$/.test(entry) && !/\.(test|spec)\.[cm]?[jt]sx?$/.test(entry)) {
      out.push(full);
    }
  }
  return out;
}

/** `[file, match]` pairs for `pattern` in the shipped source under each of `dirs`. */
function scan(dirs: string[], pattern: RegExp): string[] {
  const hits: string[] = [];
  for (const dir of dirs) {
    for (const file of sourceFiles(path.join(REPO_ROOT, dir))) {
      const text = readFileSync(file, "utf8");
      for (const m of text.matchAll(pattern)) {
        hits.push(`${path.relative(REPO_ROOT, file)}: ${m[0]}`);
      }
    }
  }
  return hits;
}

describe("T-0229 AC5 no runtime schema compile in shipped source", () => {
  it("T-0229 AC5 no file under packages/shared/src imports ajv", () => {
    expect(
      scan(["packages/shared/src"], /from\s*["']ajv|require\(\s*["']ajv|import\(\s*["']ajv/g),
    ).toEqual([]);
  });

  it("T-0229 AC5 session-plan.validate.gen.ts has no import or require", () => {
    const text = readFileSync(VALIDATOR_PATH, "utf8");
    expect(text).not.toMatch(/^\s*import\b/m);
    expect(text).not.toMatch(/\bimport\s*\(/);
    expect(text).not.toMatch(/\brequire\s*\(/);
  });

  it("T-0229 AC8 session-plan.validate.gen.ts exports only one typed binding (clean .d.ts for Deno)", () => {
    // An exported Ajv function would make tsc declare its untyped options, which Deno's checker
    // rejects on the vendored .d.ts (TS2339).
    const text = readFileSync(VALIDATOR_PATH, "utf8");
    const exports = text.match(/^export\b.*$/gm) ?? [];
    expect(exports).toHaveLength(1);
    expect(exports[0]).toMatch(
      /^export const validateSessionPlan: \(data: unknown\) => boolean = \w+;$/,
    );
  });

  it("T-0229 AC5 no new Function, Ajv .compile( or eval( in shared, engine or web source", () => {
    const dirs = ["packages/shared/src", "packages/engine/src", "apps/web/src"];
    expect(scan(dirs, /new\s+Function\s*\(|\.compile\s*\(|\beval\s*\(/g)).toEqual([]);
  });

  it("T-0229 AC5 the generator throws, naming the module, when the code needs a runtime helper", () => {
    expect(() =>
      standaloneValidatorSource(
        { type: "string", maxLength: 3 },
        { strict: true, allowUnionTypes: true, unicode: true },
      ),
    ).toThrow(/ajv\/dist\/runtime\/ucs2length/);
  });
});
