#!/usr/bin/env node
// T-0203b (D-0053 §1): compiles packages/engine/src and packages/shared/src with the workspace
// TypeScript into supabase/functions/_shared/vendor/{engine,shared}. Plain ESM .js + .d.ts, no
// bundling, so the output's own `./x.js` specifiers resolve natively in Deno. The output is
// committed; `--check` rebuilds into a temp dir and exits 1 (naming the differing file) on drift.
//
// Usage:
//   node supabase/scripts/vendor.mjs                 write the committed vendor copy
//   node supabase/scripts/vendor.mjs --check          exit 1 (and print the drifting path) on drift
//   node supabase/scripts/vendor.mjs --root <dir>     read packages/* from a different repo root
//                                                      (--check always compares against the
//                                                      committed vendor copy, not a moved output)
import {
  cpSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import ts from "typescript";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, "..", "..");
const TSCONFIG_PATH = path.join(__dirname, "tsconfig.vendor.json");
const VENDOR_DIR = path.join(REPO_ROOT, "supabase", "functions", "_shared", "vendor");
const VENDOR_REL = path.relative(REPO_ROOT, VENDOR_DIR).split(path.sep).join("/");

/** The packages vendored (shared has no dependency on engine or vice versa). */
const PACKAGES = [
  { name: "engine", src: "packages/engine/src" },
  { name: "shared", src: "packages/shared/src" },
];

const GENERATED_HEADER =
  "// GENERATED by supabase/scripts/vendor.mjs — do not edit (D-0053 §1).\n" +
  "// Source: packages/{pkg}/src. Rerun `node supabase/scripts/vendor.mjs` after an engine or\n" +
  "// shared change; CI fails on drift (`vendor.mjs --check`).\n";

function parseArgs(argv) {
  const args = { check: false, root: REPO_ROOT };
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === "--check") {
      args.check = true;
    } else if (argv[i] === "--root") {
      args.root = path.resolve(argv[++i]);
    }
  }
  return args;
}

function listFiles(dir, predicate) {
  const out = [];
  for (const entry of readdirSync(dir)) {
    const full = path.join(dir, entry);
    if (statSync(full).isDirectory()) {
      out.push(...listFiles(full, predicate));
    } else if (predicate(entry)) {
      out.push(full);
    }
  }
  return out;
}

const isTsSource = (name) => name.endsWith(".ts") && !name.endsWith(".d.ts");
const isEmitted = (name) => name.endsWith(".js") || name.endsWith(".d.ts");

/** Compiles one package's `src/**\/*.ts` into `outDir`, prefixing every emitted `.js`/`.d.ts`
 * file with the generated header. Throws on a TypeScript diagnostic. */
function compilePackage(srcDir, outDir) {
  const files = listFiles(srcDir, isTsSource);
  const configFile = ts.readConfigFile(TSCONFIG_PATH, ts.sys.readFile);
  if (configFile.error) {
    throw new Error(ts.flattenDiagnosticMessageText(configFile.error.messageText, "\n"));
  }
  const parsed = ts.parseJsonConfigFileContent(
    configFile.config,
    ts.sys,
    path.dirname(TSCONFIG_PATH),
  );
  const options = { ...parsed.options, outDir, rootDir: srcDir };
  const host = ts.createCompilerHost(options);
  const program = ts.createProgram(files, options, host);
  const emitResult = program.emit();
  const diagnostics = ts
    .getPreEmitDiagnostics(program)
    .concat(emitResult.diagnostics)
    .filter((d) => d.category === ts.DiagnosticCategory.Error);
  if (diagnostics.length > 0) {
    const msg = ts.formatDiagnosticsWithColorAndContext(diagnostics, {
      getCurrentDirectory: () => process.cwd(),
      getCanonicalFileName: (f) => f,
      getNewLine: () => "\n",
    });
    throw new Error(`vendor: TypeScript compile failed:\n${msg}`);
  }
  for (const file of listFiles(outDir, isEmitted)) {
    let contents = readFileSync(file, "utf8");
    if (!contents.startsWith(GENERATED_HEADER)) {
      contents = GENERATED_HEADER + "\n" + contents;
    }
    if (file.endsWith(".js")) {
      // Deno's type checker doesn't pair a plain `foo.js` with a sibling `foo.d.ts` the way
      // tsc's `moduleResolution: bundler`/`NodeNext` does for a bare relative import; an explicit
      // triple-slash reference makes `deno check` (and editor tooling) resolve it (D-0053 §1).
      const dtsName = `${path.basename(file, ".js")}.d.ts`;
      const reference = `/// <reference types="./${dtsName}" />\n`;
      if (!contents.includes(reference)) {
        const lines = contents.split("\n");
        const headerLineCount = GENERATED_HEADER.split("\n").length - 1;
        lines.splice(headerLineCount, 0, reference.trimEnd());
        contents = lines.join("\n");
      }
    }
    writeFileSync(file, contents, "utf8");
  }
}

/** Builds the full vendor tree (both packages) under `outRoot`, reading sources from `srcRoot`. */
function buildVendorTree(srcRoot, outRoot) {
  for (const pkg of PACKAGES) {
    const srcDir = path.join(srcRoot, pkg.src);
    const outDir = path.join(outRoot, pkg.name);
    mkdirSync(outDir, { recursive: true });
    compilePackage(srcDir, outDir);
  }
}

/** Recursively compares two directory trees. Returns the first relative path that differs, or
 * null when the trees are identical (same files, same bytes). */
function diffTrees(dirA, dirB) {
  const relFiles = (dir) => {
    const out = [];
    const walk = (d, prefix) => {
      for (const entry of readdirSync(d).sort()) {
        const full = path.join(d, entry);
        const rel = prefix ? `${prefix}/${entry}` : entry;
        if (statSync(full).isDirectory()) {
          walk(full, rel);
        } else {
          out.push(rel);
        }
      }
    };
    if (existsSync(dir)) walk(dir, "");
    return out;
  };
  const filesA = relFiles(dirA);
  const filesB = relFiles(dirB);
  const setB = new Set(filesB);
  for (const rel of filesA) {
    if (!setB.has(rel)) return rel;
    const a = readFileSync(path.join(dirA, rel));
    const b = readFileSync(path.join(dirB, rel));
    if (!a.equals(b)) return rel;
  }
  for (const rel of filesB) {
    if (!filesA.includes(rel)) return rel;
  }
  return null;
}

export function main(argv) {
  const args = parseArgs(argv);
  const tmpRoot = mkdtempSync(path.join(tmpdir(), "workoutlab-vendor-"));
  try {
    const builtDir = path.join(tmpRoot, "vendor");
    try {
      buildVendorTree(args.root, builtDir);
    } catch (err) {
      process.stderr.write(`${err.message}\n`);
      return 1;
    }
    if (args.check) {
      const diff = diffTrees(VENDOR_DIR, builtDir);
      if (diff !== null) {
        console.log(`${VENDOR_REL}/${diff}`);
        return 1;
      }
      return 0;
    }
    rmSync(VENDOR_DIR, { recursive: true, force: true });
    mkdirSync(VENDOR_DIR, { recursive: true });
    cpSync(builtDir, VENDOR_DIR, { recursive: true });
    return 0;
  } finally {
    rmSync(tmpRoot, { recursive: true, force: true });
  }
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  process.exit(main(process.argv.slice(2)));
}
