// Generates src/api.gen.ts from api/openapi.yaml (D-0037 §10). Run: pnpm gen:api.
// The AC13 drift test calls generateApiTypes() in-process and compares bytes.
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";
import * as prettier from "prettier";

export const SPEC_PATH = fileURLToPath(new URL("../../../api/openapi.yaml", import.meta.url));
export const OUT_PATH = fileURLToPath(new URL("../src/api.gen.ts", import.meta.url));

const HEADER =
  "// GENERATED by packages/shared/scripts/gen-api.ts from api/openapi.yaml. Do not edit.\n" +
  "// Regenerate with `pnpm --filter @workoutlab/shared gen:api` (D-0037 §10).\n\n";

export async function generateApiTypes(): Promise<string> {
  const spec = await readFile(SPEC_PATH, "utf8");
  const ast = await openapiTS(spec, { alphabetize: false });
  const source = HEADER + astToString(ast);
  const config = (await prettier.resolveConfig(OUT_PATH)) ?? {};
  return prettier.format(source, { ...config, filepath: OUT_PATH });
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  await writeFile(OUT_PATH, await generateApiTypes());
  console.log(`wrote ${OUT_PATH}`);
}
