// Generates src/api.gen.ts, src/session-plan.schema.gen.ts and src/session-plan.validate.gen.ts
// from api/openapi.yaml (D-0037 §10, D-0043, D-0117). Run: pnpm gen:api (tsx, so it runs on every
// Node 22).
// The AC13 drift test calls generateApiTypes(), generateSessionPlanSchema() and
// generateSessionPlanValidator() in-process and compares bytes with the committed files.
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { Ajv2020, type Options } from "ajv/dist/2020.js";
import standaloneCode from "ajv/dist/standalone/index.js";
import openapiTS, { astToString } from "openapi-typescript";
import * as prettier from "prettier";
import { parse } from "yaml";

export const SPEC_PATH = fileURLToPath(new URL("../../../api/openapi.yaml", import.meta.url));
export const OUT_PATH = fileURLToPath(new URL("../src/api.gen.ts", import.meta.url));
export const PLAN_SCHEMA_PATH = fileURLToPath(
  new URL("../src/session-plan.schema.gen.ts", import.meta.url),
);
export const VALIDATOR_PATH = fileURLToPath(
  new URL("../src/session-plan.validate.gen.ts", import.meta.url),
);

const HEADER =
  "// GENERATED by packages/shared/scripts/gen-api.ts from api/openapi.yaml. Do not edit.\n" +
  "// Regenerate with `pnpm --filter @workoutlab/shared gen:api` (D-0037 §10).\n\n";

export async function generateApiTypes(): Promise<string> {
  const spec = await readFile(SPEC_PATH, "utf8");
  const ast = await openapiTS(spec, { alphabetize: false });
  const source = HEADER + astToString(ast);
  const config = (await prettier.resolveConfig(OUT_PATH)) ?? {};
  return prettier.format(source, { ...config, filepath: OUT_PATH });
}

const ANNOTATIONS = new Set(["description", "example", "examples", "discriminator"]);

/** Drops OpenAPI annotations and rewrites `#/components/schemas/X` refs to `#/$defs/X`. */
function toJsonSchema(node: unknown): unknown {
  if (Array.isArray(node)) return node.map(toJsonSchema);
  if (!node || typeof node !== "object") return node;
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(node)) {
    if (ANNOTATIONS.has(k) || k.startsWith("x-")) continue;
    if (k === "$ref" && typeof v === "string") {
      out[k] = v.replace("#/components/schemas/", "#/$defs/");
    } else if (k === "properties" && v && typeof v === "object") {
      // Property names are data, not keywords: keep every name, clean each value.
      out[k] = Object.fromEntries(
        Object.entries(v).map(([name, sub]) => [name, toJsonSchema(sub)]),
      );
    } else {
      out[k] = toJsonSchema(v);
    }
  }
  return out;
}

/** Component names reachable from `root` through `$ref`, `root` first, then sorted. */
function closure(schemas: Record<string, unknown>, root: string): string[] {
  const seen = new Set<string>([root]);
  const walk = (node: unknown): void => {
    if (Array.isArray(node)) return node.forEach(walk);
    if (!node || typeof node !== "object") return;
    for (const [k, v] of Object.entries(node)) {
      if (k === "$ref" && typeof v === "string") {
        const name = v.slice("#/components/schemas/".length);
        if (!seen.has(name)) {
          seen.add(name);
          walk(schemas[name]);
        }
      } else walk(v);
    }
  };
  walk(schemas[root]);
  return [root, ...[...seen].filter((n) => n !== root).sort()];
}

/**
 * The `SessionPlan` component and everything it references, as one JSON Schema 2020-12 document.
 * `parseSessionPlan()` validates `sessions.plan` against it (precompiled by gen:api, D-0043, D-0117).
 */
export async function sessionPlanSchema(): Promise<object> {
  const spec = parse(await readFile(SPEC_PATH, "utf8")) as {
    components: { schemas: Record<string, unknown> };
  };
  const schemas = spec.components.schemas;
  const defs = Object.fromEntries(
    closure(schemas, "SessionPlan").map((name) => [name, toJsonSchema(schemas[name])]),
  );
  const schema = {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    $id: "https://workoutlab.local/api/session-plan",
    $ref: "#/$defs/SessionPlan",
    $defs: defs,
  };
  return schema;
}

/** `src/session-plan.schema.gen.ts`: {@link sessionPlanSchema} as a `const` (D-0043). */
export async function generateSessionPlanSchema(): Promise<string> {
  const schema = await sessionPlanSchema();
  const source =
    "// GENERATED by packages/shared/scripts/gen-api.ts from api/openapi.yaml. Do not edit.\n" +
    "// The SessionPlan component and its references, for parseSessionPlan() (D-0043).\n\n" +
    `export const SESSION_PLAN_SCHEMA = ${JSON.stringify(schema)} as const;\n`;
  const config = (await prettier.resolveConfig(PLAN_SCHEMA_PATH)) ?? {};
  return prettier.format(source, { ...config, filepath: PLAN_SCHEMA_PATH });
}

/** The Ajv options of the precompiled SessionPlan validator (D-0043 §3, D-0117 §1). */
export const VALIDATOR_OPTIONS = {
  strict: true,
  allErrors: false,
  allowUnionTypes: true,
  unicode: false,
} as const satisfies Options;

/**
 * Ajv standalone (ESM) source for `schema`. The output must be self-contained: the shipped app
 * never compiles code at runtime (CSP `script-src 'self'`, D-0117), and the Deno import map has no
 * `ajv/dist/runtime/*` entries. So any `require(...)` or `import` in Ajv's output is an error that
 * names the module, not something to emit (D-0117 §1).
 */
export function standaloneValidatorSource(
  schema: object,
  options: Options = VALIDATOR_OPTIONS,
): string {
  const ajv = new Ajv2020({ ...options, code: { source: true, esm: true } });
  const code = standaloneCode(ajv, ajv.compile(schema));
  const modules = [
    ...[...code.matchAll(/require\(\s*["'`]([^"'`]+)["'`]\s*\)/g)].map((m) => m[1]),
    ...[...code.matchAll(/\bimport\b[^;]*?["'`]([^"'`]+)["'`]/g)].map((m) => m[1]),
  ];
  if (modules.length > 0 || /\brequire\(|\bimport\b/.test(code)) {
    const named = modules.length > 0 ? modules.join(", ") : "(unknown module)";
    throw new Error(
      `gen-api: the standalone validator needs a runtime import (${named}); ` +
        "a precompiled validator must be self-contained (D-0117 §1)",
    );
  }
  return code;
}

/**
 * `src/session-plan.validate.gen.ts`: the SessionPlan validator, compiled at codegen time so the
 * shipped app runs no `new Function` (D-0117). `parseSessionPlan()` is its only consumer.
 */
export async function generateSessionPlanValidator(): Promise<string> {
  const code = standaloneValidatorSource(await sessionPlanSchema());
  // Ajv's ESM exports re-export its internal function, whose untyped destructured options give
  // tsc a declaration that Deno's checker rejects (TS2339 on the vendored .d.ts). Keep the Ajv
  // function module-private and export one typed binding, so the declaration is a single line.
  const exports = /^"use strict";export const validate = (\w+);export default \1;/.exec(code);
  if (!exports) {
    throw new Error("gen-api: unexpected Ajv standalone export preamble (D-0117 §1)");
  }
  const source =
    "// GENERATED by packages/shared/scripts/gen-api.ts from api/openapi.yaml. Do not edit.\n" +
    "// Ajv standalone validator for SESSION_PLAN_SCHEMA, used by parseSessionPlan() (D-0117).\n" +
    "// @ts-nocheck\n\n" +
    '"use strict";' +
    code.slice(exports[0].length) +
    `\nexport const validateSessionPlan: (data: unknown) => boolean = ${exports[1]};\n`;
  const config = (await prettier.resolveConfig(VALIDATOR_PATH)) ?? {};
  return prettier.format(source, { ...config, filepath: VALIDATOR_PATH });
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  await writeFile(OUT_PATH, await generateApiTypes());
  console.log(`wrote ${OUT_PATH}`);
  await writeFile(PLAN_SCHEMA_PATH, await generateSessionPlanSchema());
  console.log(`wrote ${PLAN_SCHEMA_PATH}`);
  await writeFile(VALIDATOR_PATH, await generateSessionPlanValidator());
  console.log(`wrote ${VALIDATOR_PATH}`);
}
