// Generates src/api.gen.ts and src/session-plan.schema.gen.ts from api/openapi.yaml (D-0037 §10,
// D-0043). Run: pnpm gen:api (tsx, so it runs on every Node 22).
// The AC13 drift test calls generateApiTypes() and generateSessionPlanSchema() in-process and
// compares bytes with the committed files.
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";
import * as prettier from "prettier";
import { parse } from "yaml";

export const SPEC_PATH = fileURLToPath(new URL("../../../api/openapi.yaml", import.meta.url));
export const OUT_PATH = fileURLToPath(new URL("../src/api.gen.ts", import.meta.url));
export const PLAN_SCHEMA_PATH = fileURLToPath(
  new URL("../src/session-plan.schema.gen.ts", import.meta.url),
);

const HEADER =
  "// GENERATED by packages/shared/scripts/gen-api.ts from api/openapi.yaml. Do not edit.\n" +
  "// Regenerate with `pnpm --filter @workoutlab/shared gen:api` (D-0037 §10).\n\n";

export async function generateApiTypes(): Promise<string> {
  const spec = await readFile(SPEC_PATH, "utf8");
  const ast = await openapiTS(spec, { alphabetize: false });
  const source = HEADER + astToString(ast);
  const config = (await prettier.resolveConfig(OUT_PATH)) ?? {};
  return prettier.format(source, { ...config, filepath: OUT_PATH });
}

const ANNOTATIONS = new Set(["description", "example", "examples", "discriminator"]);

/** Drops OpenAPI annotations and rewrites `#/components/schemas/X` refs to `#/$defs/X`. */
function toJsonSchema(node: unknown): unknown {
  if (Array.isArray(node)) return node.map(toJsonSchema);
  if (!node || typeof node !== "object") return node;
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(node)) {
    if (ANNOTATIONS.has(k) || k.startsWith("x-")) continue;
    if (k === "$ref" && typeof v === "string") {
      out[k] = v.replace("#/components/schemas/", "#/$defs/");
    } else if (k === "properties" && v && typeof v === "object") {
      // Property names are data, not keywords: keep every name, clean each value.
      out[k] = Object.fromEntries(Object.entries(v).map(([name, sub]) => [name, toJsonSchema(sub)]));
    } else {
      out[k] = toJsonSchema(v);
    }
  }
  return out;
}

/** Component names reachable from `root` through `$ref`, `root` first, then sorted. */
function closure(schemas: Record<string, unknown>, root: string): string[] {
  const seen = new Set<string>([root]);
  const walk = (node: unknown): void => {
    if (Array.isArray(node)) return node.forEach(walk);
    if (!node || typeof node !== "object") return;
    for (const [k, v] of Object.entries(node)) {
      if (k === "$ref" && typeof v === "string") {
        const name = v.slice("#/components/schemas/".length);
        if (!seen.has(name)) {
          seen.add(name);
          walk(schemas[name]);
        }
      } else walk(v);
    }
  };
  walk(schemas[root]);
  return [root, ...[...seen].filter((n) => n !== root).sort()];
}

/**
 * The `SessionPlan` component and everything it references, as one JSON Schema 2020-12 document.
 * `parseSessionPlan()` validates `sessions.plan` against it at runtime (D-0043).
 */
export async function generateSessionPlanSchema(): Promise<string> {
  const spec = parse(await readFile(SPEC_PATH, "utf8")) as {
    components: { schemas: Record<string, unknown> };
  };
  const schemas = spec.components.schemas;
  const defs = Object.fromEntries(
    closure(schemas, "SessionPlan").map((name) => [name, toJsonSchema(schemas[name])]),
  );
  const schema = {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    $id: "https://workoutlab.local/api/session-plan",
    $ref: "#/$defs/SessionPlan",
    $defs: defs,
  };
  const source =
    "// GENERATED by packages/shared/scripts/gen-api.ts from api/openapi.yaml. Do not edit.\n" +
    "// The SessionPlan component and its references, for parseSessionPlan() (D-0043).\n\n" +
    `export const SESSION_PLAN_SCHEMA = ${JSON.stringify(schema)} as const;\n`;
  const config = (await prettier.resolveConfig(PLAN_SCHEMA_PATH)) ?? {};
  return prettier.format(source, { ...config, filepath: PLAN_SCHEMA_PATH });
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  await writeFile(OUT_PATH, await generateApiTypes());
  console.log(`wrote ${OUT_PATH}`);
  await writeFile(PLAN_SCHEMA_PATH, await generateSessionPlanSchema());
  console.log(`wrote ${PLAN_SCHEMA_PATH}`);
}
